apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetworld
spec:
  selector:
    matchLabels:
      app: demofargate
  replicas: 1 
  template: 
    metadata:
      labels:
        app: demofargate
    spec:
      containers:
      - name: dotnetworld
        image: 195275634008.dkr.ecr.ap-south-1.amazonaws.com/demoecr:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: dotnetworld
 namespace: demo-fargate
 labels: 
   app: demofargate
spec:
 type: ClusterIp
 selector:
   app: demofargate
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32080
 selector:
   app: demofargate
