apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetworld
  namespace: demo-fargate
  labels: 
    app: demofargate
spec:
  selector:
    matchLabels:
      app: demofargate
  replicas: 1 
  template: 
    metadata:
      labels:
        app: demofargate
    spec:
      containers:
      - name: dotnetworld
        image: 034362066826.dkr.ecr.ap-south-1.amazonaws.com/demoecrrepo:IMAGEID
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: dotnetworld
 namespace: demo-fargate
 labels: 
   app: demofargate
spec:
 type: ClusterIP
 selector:
   app: demofargate
 ports:
   - name: http
     protocol: TCP
     port: 80
     targetPort: 80
